before:
  hooks:
  - go mod download
builds:
- id: default-build
  main: ./cmd/gocompat/main.go
  binary: gocompat
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - '386'
  - amd64
  - arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
archives:
- id: default-archive
  builds:
  - default-build
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
